import images from "../../assets/products/images";

const products = [
  {
    name: "Essential White T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[0],
  },
  {
    name: "Essential Black Long sleeves T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[1],
  },
  {
    name: "Essential Grey T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[2],
  },
  {
    name: "Long sleeves Baseball T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[3],
  },
  {
    name: "White tight fit premium T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[4],
  },
  {
    name: "Essential Yellow T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[5],
  },
  {
    name: "Essential Red Polo-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[6],
  },
  {
    name: "Essential Black Om logo T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[7],
  },
  {
    name: "Essential Red T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[8],
  },
  {
    name: "Essential Blue premium T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[9],
  },
  {
    name: "Essential White Polo-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[10],
  },
  {
    name: "Essential Yellow T-shirt",
    price: 10,
    sex: "male",
    cat: "tshirt",
    image: images.men.tshirt[11],
  },
  {
    name: "Essential Long sleeve Baseball T-shirt",
    price: 10,
    sex: "female",
    cat: "tshirt",
    image: images.women.tshirt[0],
  },
  {
    name: "Rocket logo Blue T-shirt",
    price: 10,
    sex: "female",
    cat: "tshirt",
    image: images.women.tshirt[1],
  },
  {
    name: "Essential Red crop-top",
    price: 10,
    sex: "female",
    cat: "tshirt",
    image: images.women.tshirt[2],
  },
  {
    name: "Essential Red V-neck T-shirt",
    price: 10,
    sex: "female",
    cat: "tshirt",
    image: images.women.tshirt[3],
  },
  {
    name: "Essential White V-neck T-shirt",
    price: 10,
    sex: "female",
    cat: "tshirt",
    image: images.women.tshirt[4],
  },
];

export default products;
